### ISSUE TITLE
data loading from db for dedupe: tuples not as expected?

### ISSUE THREAD

**Issue by f-hafner** [f-hafner/mag_sample#6]
not all records have their year_range as an expected tuple. this gives errors in the training and linking steps for NSF-MAG: we expect the year_range from NSF to be as `(year, )` and the year_range from MAG to be `(startyear, endyear)`. But sometimes tuples do not have the expected length, and sometimes other types are passed (see traceback below).

```bash
Traceback (most recent call last):
  File "/home/christoph/anaconda3/envs/science-career-tempenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/christoph/anaconda3/envs/science-career-tempenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/christoph/anaconda3/envs/science-career-tempenv/lib/python3.9/site-packages/dedupe/core.py", line 137, in __call__
    self.fieldDistance(record_pairs)
  File "/home/christoph/anaconda3/envs/science-career-tempenv/lib/python3.9/site-packages/dedupe/core.py", line 148, in fieldDistance
    distances = self.data_model.distances(records)
  File "/home/christoph/anaconda3/envs/science-career-tempenv/lib/python3.9/site-packages/dedupe/datamodel.py", line 84, in distances
    distances[i, start:stop] = compare(record_1[field],
  File "/home/christoph/mag_sample/src/dataprep/helpers/comparator_functions.py", line 167, in compare_range_from_tuple
    elif len(b) == 1:
TypeError: object of type 'int' has no len()
``` 

most probably a problem with loading the data from the database to the form for dedupe.

**Comment by chrished** [comment]
I think this has been solved by @f-hafner, at least the rerun for physics seems to work on [christoph/link_grants](https://github.com/f-hafner/mag_sample/tree/christoph/link_grants).
